// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV83TZaNL6WQZ1aWWUW2JOQRsjrK1cQlg',
    appId: '1:44413210646:web:0fa024981086189598a537',
    messagingSenderId: '44413210646',
    projectId: 'ifa-21312055-90f9e',
    authDomain: 'ifa-21312055-90f9e.firebaseapp.com',
    storageBucket: 'ifa-21312055-90f9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaXOmb_xxfkdPys1JZobXGVbSDlMSb-Ak',
    appId: '1:44413210646:android:1911900cd0c58b5498a537',
    messagingSenderId: '44413210646',
    projectId: 'ifa-21312055-90f9e',
    storageBucket: 'ifa-21312055-90f9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5sn2Dlu3Wvel9jdchpdMLpFx-NJTskGY',
    appId: '1:44413210646:ios:87565a92692cf31998a537',
    messagingSenderId: '44413210646',
    projectId: 'ifa-21312055-90f9e',
    storageBucket: 'ifa-21312055-90f9e.appspot.com',
    iosBundleId: 'com.example.ifa21312055',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5sn2Dlu3Wvel9jdchpdMLpFx-NJTskGY',
    appId: '1:44413210646:ios:a40c3f61e45ca77f98a537',
    messagingSenderId: '44413210646',
    projectId: 'ifa-21312055-90f9e',
    storageBucket: 'ifa-21312055-90f9e.appspot.com',
    iosBundleId: 'com.example.ifa21312055.RunnerTests',
  );
}
