// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiUdU669KRJ8L-toZTRrUZTeqv5Y3nI8U',
    appId: '1:1081605988382:web:655558bb0f8f805f5ece0f',
    messagingSenderId: '1081605988382',
    projectId: 'ifa-21312055',
    authDomain: 'ifa-21312055.firebaseapp.com',
    storageBucket: 'ifa-21312055.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFajNQdr1SuaglJQiAtUEp8n1P3Y4TWdQ',
    appId: '1:1081605988382:android:d60e149ccd65eff55ece0f',
    messagingSenderId: '1081605988382',
    projectId: 'ifa-21312055',
    storageBucket: 'ifa-21312055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQP_tLeQG_AIEpx1ZT-A6J8AVzJR3KSE',
    appId: '1:1081605988382:ios:fc1d604f201ff86e5ece0f',
    messagingSenderId: '1081605988382',
    projectId: 'ifa-21312055',
    storageBucket: 'ifa-21312055.appspot.com',
    iosBundleId: 'com.example.ifa21312055',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQP_tLeQG_AIEpx1ZT-A6J8AVzJR3KSE',
    appId: '1:1081605988382:ios:9ddea4a5305ff5595ece0f',
    messagingSenderId: '1081605988382',
    projectId: 'ifa-21312055',
    storageBucket: 'ifa-21312055.appspot.com',
    iosBundleId: 'com.example.ifa21312055.RunnerTests',
  );
}
